libgit2/git2go

config.go
ConfigFindGlobal -> git_config_find_global
ConfigFindSystem -> git_config_find_system
ConfigFindXDG    -> git_config_find_xdg
In addition you get one or two minor changes from gofmt.
-T
=> Add Go functions for git_config_find_* functions

index.go, index_test.go
These are quite useful, but we don't have them yet.
=> Add a few basic index operations

branch.go
For issue: https://github.com/libgit2/git2go/issues/209
=> Free reference resource allocated by libgit2 during go garbage collecting

clone.go, remote.go
This wasn't ported together with the rest, but it does exhibit the same
issues, so let's port it over now.
=> Make the network code use handles

repository.go
=> Add method to check if repo's HEAD is detached

reference.go, reference_test.go
Add `Reference.IsNote()` and `ReferenceIsValidName()`.
=> Reference additions

tree.go, tree_test.go
Add support for `git_tree_entry_byid`.
=> Find tree entry by id

repository.go, tag.go, tag_test.go, wrapper.c
Add `TagsCollection`.
Add support for `git_tag_list`, `git_tag_list_match`, `git_tag_foreach`, `git_tag_create_lightweight`.
=> Add more support for tags

merge.go, merge_test.go
While here, test MergeBase as well.
=> Wrap MergeBases

object.go, object_test.go
Adds support for `git_object_peel`.
=> Add ability to peel any git object

branch.go, merge.go
Fix some memory leaks caused by CStrings not being freed. Fixes #214.
=> Memleak fixes

ignore.go
This adds support for `git_ignore_*` functions.
=> Add support for ignore

index.go
=> Fix memory leaks in NewIndex() and OpenIndex()

repository.go
=> Add missing RepositoryOpenExtended arguments

walk.go
Reference: https://libgit2.github.com/libgit2/#HEAD/group/revwalk/git_revwalk_simplify_first_parent
=> Add RevWalk.SimplifyFirstParent()

diff.go
Hi, I'm not sure about `libgit2`, but I need `git diff --cached` -ish features.
According to https://libgit2.github.com/libgit2/#HEAD/group/diff/git_diff_tree_to_index:
It requires `add_git_diff_tree_to_index`. So I've added it.
Thanks.
=> Add git_diff_tree_to_index

diff.go, repository.go, status.go
Added some tiny stuff I needed. I did this on the next branch, but it looks like some of this is available on previous versions on libgit2 (if i'm not mistaken). Let me know if anything is wrong and I'll fix it quickly!
=> Add some constants and repository methods.

reset.go
Added support for default reset behavior
=> ResetDefaultToCommit maps git_reset_default

repository.go, tag.go
Added support for removal of a Tag
=> Tag Remove

branch.go, status.go
- BranchAll maps GIT_BRANCH_ALL
- StatusConflicted maps GIT_STATUS_CONFLICTED
=> Enum Mappings

checkout.go, clone.go, wrapper.c
- Added CheckoutNotifyType mapping git_checkout_notify_t
- Added CheckoutOpts.NotifyFlags of type CheckoutNotifyType
- Added CheckoutNotifyCallback mapping git_checkout_notify_cb
- Added CheckoutProgressCallback mapping git_checkout_progress_cb
=> Checkout callbacks

index.go, index_test.go
Here is a simple PR to implement git_index_remove_directory service into index wrapper.
=> Implement git_index_remove_directory in index wrapper

.travis.yml
The other branches will get built as part of a PR.
=> travis: only build master and next

blob.go, commit.go, object.go, tag.go, tree.go
(Re)introduce an interface for all kinds of objects and use it for tagging objects.
=> Tag any kind of object

repository.go, repository_test.go
This change adds support for CreateCommitFromIds from libgit2.
=> Add support for CreateCommitFromIds

mempack.go, mempack_test.go
This allows the creation of git packfiles without needing to write them
to the filesystem.
=> Add support for mempack

git_static.go, object.go, odb.go
=> Uprev vendored libgit2 to v.0.28

tag.go, tree.go
=> Fixes #513 - Segfault during tree walk

indexer.go, indexer_test.go, odb.go, odb_test.go, wrapper.c
This allows for implementations of git servers written in Go.
=> Add support for indexers and alternate odb packfiles

git_dynamic.go, git_static.go, script/build-libgit2.sh
This uprevs libgit2 to the latest and greatest.
=> Uprev vendor/libgit2 to v0.99

README.md
This should make importing the library clearer/more obvious.
=> Update README.md to clarify the import

remote.go
fix for https://github.com/libgit2/git2go/issues/553
=> fix SIGSEGV on double free for Cred object

README.md, git_dynamic.go, git_static.go, go.mod
This uprevs libgit2 to the latest and greatest.
=> Uprev vendor/libgit2 to v1.0

signature.go
This pull request mitigate issue #559.
=> Check nil signature to prevent panic

merge.go, merge_test.go
This change adds support for MergeBaseMany, MergeBasesMany, and
MergeBaseOctopus.
=> Support more MergeBase functions

merge_test.go, repository.go
=> Support git_repository_message, git_repository_message_remove

repository.go, repository_test.go
=> Implement git_repository_set_config

repository.go, repository_test.go
add wrapper for `git_repository_item_path`
(cherry picked from commit a4d202ed7b025331ee4a63ebc38f62519cee4750)
=> Git repository item path (#757)

commit.go, repository.go
This change adds the wrapper for `git_commit_create_with_signature`.
=> Add `CreateCommitWithSignature`

deprecated.go, remote.go
This change adds a few more deprecation messages just before we remove
them.
=> Prepare for the v1.2.0 release

README.md
(cherry picked from commit 533c82f2707b8ad2f0f667867b3ea91ec08667aa)
=> Fix replace statement example in README.md (#859)

README.md
This is a release-specific change corresponding to #886
=> readme: link to godoc for current main branch
