submodule.go
submodule_test.go

This pull request fixes a panic with repo.ForeachSubmodule caused by a wrong signature of a function that is being called from libgit2. The first commit introduces a failing test and the second commit fixes the issue.

Submodule foreach fix

---

patch_test.go

When you have `diff.noprefix` or `diff.mnemonicprefix` configuration set to true globally, such as in ~/.gitconfig, `TestPatch` fails.
This Pull Request fixes this problem by setting OldPrefix and NewPrefix explicitly.

Fix test to force diff prefixes.

---

graph.go

This adds support for `git_graph_ahead_behind` and `git_graph_descendant_of` respectively wrapped as `Repository.GraphAheadBehind` and `Repository.GraphDescendantOf`.

Add bindings for git_graph_* methods

---

reset.go
reset_test.go

Hey all, I'm not super experienced with go and C, but I'm working on something that requires git reset. This should solve https://github.com/libgit2/git2go/issues/107.
Feel free to let me know if anything looks wrong in either implementation or style! I based this off of the `next` branch because that is what I'm using, not sure how much work it would be to update it for `master`.
Adds a new method to *Repository called ResetToCommit as well as constants for
the three reset modes that libgit2 currently supports. This does not need to be
limited to Commit, we actually just need something with a gitObject, which blobs
and other Objects have, they will just require different methods. I only need
to be able to reset to commits, so that's all I'm implementing right now.
Also adds a test which …

Add support for libgit2's git_reset.

---

script/check-MakeGitError-thread-lock.go

If I am not mistaken, the `script/check-MakeGitError-thread-lock.go` is only needed and used in one place:
https://github.com/libgit2/git2go/blob/a4d5118374607f107af8063797f62e6a9f7470aa/Makefile#L7
It is used in `go run script/check-MakeGitError-thread-lock.go`.
However, the `install` target of the same Makefile performs `go install ./...`:
https://github.com/libgit2/git2go/blob/a4d5118374607f107af8063797f62e6a9f7470aa/Makefile#L11
Which ends up installing a `script` binary into user's $GOPATH/bin.
Many people have $GOPATH/bin as part of their $PATH, and if I am correct that `script` is not needed in any other way except that one place where `go run script/check-MakeGitError-thread-lock.go` uses it, then it's better to avoid installing the `script` binary to user's $GOPATH/bin and …

Avoid installing script binary to user's $GOPATH/bin.

---

blame_test.go
blob_test.go
branch_test.go
cherrypick_test.go
clone_test.go
diff_test.go
git_test.go
index_test.go
merge_test.go
note_test.go
object_test.go
odb_test.go
patch_test.go
push_test.go
reference_test.go
remote_test.go
revparse_test.go
status_test.go
submodule_test.go
tag_test.go

Some test repositories are not correctly removed after the tests
did run. Fix by introducing a function that is to be used for
cleaning up temporary test repositories.

tests: always clean up temporary repository dirs

---

blob.go
diff.go
git.go
handles.go
index.go
odb.go
odb_test.go
packbuilder.go
submodule.go
tree.go

This pull request fixes issues with Go callbacks that are handed over to C functions. As of Go 1.4 it is not possible to hand over Go pointers into C code as the garbage collector is allowed to copy around the stack, causing pointers to become invalid (see golang/go#8310 and golang/go#10303 for more information).
@carlosmn proposed an interface HandleList for pointer indirection which provides a global map of data that is to be tracked. Instead of handing in pointers we now instead hand over an index that points to the corresponding entry in this map.
This PR adds the HandleList implemented by @carlosmn, fixes some issues with it and adjusts code that hands over Go pointers into C code to use handles instead. Still missing is the remote.go code, as I am running into some error there …

[WIP/RFC] Pointer indirection

---

git.go

My use case is a client which caches OAuth2 access tokens for authentication. When the access token expires, the client gets a new one using a refresh token.
Unfortunately, the only surefire way to know the access token has expired is to use it until authentication fails. So the client needs a way to know when authentication failed, and GIT_EAUTH seems to be the right error code to check for.

Add error code matching GIT_EAUTH for authentication failures

---

reference.go
remote.go
repository.go

libgit2 0.22.1 compiled x64 RelWithDebug using Visual Studio 2013 combined with the v22 branch crashes when running the unit tests. I've traced this to the use of `C.free(unsafe.Pointer(csig))` in some places instead of `C.git_signature_free(csig)` as in other places. Switching to `git_signature_free` seems to fix this. I don't know why in some places `free` was used over `git_signature_free`.

use git_signature_free (fix test crash on Windows)

---

handles.go

Before this change, there were no users of `slot` int variable in the Go world (just a pointer to it that ended up in C world only), so Go's garbage collector would free it and its value could not retrieved later (once a pointer to it comes back to Go world from C world).
Keep a pointer to it in the Go world so that does not happen.
Fixes #218. See that issue for a detailed analysis of the problem, and a reproducible test case (in a package that imports this one).
Please review for correctness and style, feedback is welcome.
There are many, many ways of doing the task of "keeping some reference to `slot` in Go so it's not GCed, including keeping a pointer to it as `*int`, or `unsafe.Pointer`, or `interface{}`. I've reused the `set` map since it seemed appropriate, but a new/different map …

[next] Prevent slot int variable from being GCed.

---

handles.go

This is a backport of the fix for `next` branch (PR #219) to `master` branch.
Fixes #218 completely.

[master] Prevent slot int variable from being GCed.

---

describe.go
describe_test.go

Includes `git_describe_commit` and `git_describe_workdir`, with all existing describe and format options.

Add git-describe support

---

clone.go
clone_test.go
wrapper.c

The `void` pointer that is being passed when populating the clone
options' payload is currently being freed as soon as the
populating function returns. As the memory it points to is only
ever being accessed after the function returns this will cause
invalid memory access.
Fix this by removing the call to `free`. As we cannot know
what the caller is passing as content of the `void` pointer we
cannot take responsibility for `free`ing it. This has to be the
responsibility of the caller, instead.

clone: do not free clone options' payload

---

blob.go
commit.go
describe.go
index_test.go
object.go
object_test.go
reference.go
repository.go
reset.go
revparse.go
revparse_test.go
tag.go
tree.go

An Object should be about representing a libgit2 object rather than
showing which methods it should support.
Change any return of Object to *Object and provide methods to convert
between this and the particular type.
---
It's a large change with the types, but we don't get another opportunity to get it into mainline for quite a while.

Move from an Object interface to a type

---

config.go
config_test.go

A solution to `get_string called on a live config object` errors when attempting a string lookup on a config object.

Fix bug in Config LookupString

---

remote.go

The Fetch/Push operations didn't allocate the git_*_options structure
and this causes a memory problem in the libgit2 code. Following the
example of Clone operation, the Fetch/Push functions allocates the
options structure before calling the C.

Fix Fetch/Push memory allocation problems

---

index.go

Fix a memory leak in `Index.EntryByPath` method, which I introduced in #260.

Fix a memory leak in Index.EntryByPath()

---

index.go

This adds support for `git_index_find()` and `git_index_find_prefix()`.

Add Index.Find() and Index.FindPrefix()

---

odb.go
odb_test.go

hi, this exposes git_odb_read_header, which is much faster for discovering size for a given OID.

Expose git_odb_read_header as Odb.ReadHeader.

---

handles.go
merge.go
odb.go
wrapper.c

See http://tip.golang.org/cmd/cgo/#hdr-Passing_pointers .

handles, merge, odb: changes for Go 1.6 pointer passing rules

---

handles.go

With the change to 1.6 rules, we couldn't use the Go pointers, so we
went with casting the list indices into pointers.
The runtime does not like this, however. It will sometimes detect that
we have a pointer with a very small value and consider it an invalid
pointer, bringing down the application with it.
Work around that by asking libc for the smallest amount of memory it'll
give us so we have an actual allocated pointer to use. We then use this
pointer value as the key in our map to find the Go object we're
tracking.

handles: use real pointers to keep track of handles

---

odb.go

It might be needed when one is writing `git cat-file --batch` equivalent
which has output format
<sha1> SP <type> SP <size> LF
<contents> LF

odb: Expose git_odb_object_type() as OdbObject.Type()

---

diff.go

This adds a String() function to DiffStats which returns the output of git_diff_stats_to_buf.

Add DiffStats String

---

blame_test.go
blob_test.go
branch_test.go
cherrypick_test.go
clone_test.go
config_test.go
describe_test.go
diff_test.go
git_test.go
index_test.go
merge_test.go
note_test.go
object_test.go
odb_test.go
patch_test.go
push_test.go
reference_test.go
remote_test.go
reset_test.go
revparse_test.go
status_test.go
submodule_test.go
tag_test.go
tree_test.go

This saves about 1s, or 1/3 of the test runtime. The linking is still
much slower, but this we can control.

Run the tests in parallel

---

walk.go

We were seeing an issue with conversion of errors, and it ends up an error was being converted to `GitError rather than `*GitError`.

Fix: Error conversion issue

---

branch.go

The BranchIterator.ForEach currently returns the ErrIterOver error if no
error had occured during the iteration. This leads to a rather unhelpful
blank error message with the error code -31 when iterating over the
branches.
This commit adds a check for ErrIterOver at the end of the ForEach
method so that the client code only has to worry about checking for nil
as apose to checking for the ErrIterOver error.

Add check for ErrIterOver in BranchIterator.ForEach

---

git_test.go

The seedTestRepo() test helper function leaves the seeded repo in an unusual state because the index is not written before the index tree is written. To correct, simply write the index before writing the index tree.
**BEFORE** change, seedTestRepo() leaves repo in this state:
> On branch master
> Changes to be committed:
>   (use "git reset HEAD <file>..." to unstage)
> 
> 	deleted:    README
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
> 	README
> 
**AFTER** change, seedTestRepo() leaves repo in this state:
> On branch master
> nothing to commit, working directory clean

Write index before writing index tree in seedTestRepo test helper

---

credentials.go

Allowing to use public and private keys from memory
without reading them from disk and without using an
ssh agent.
Signed-off-by: David Calavera <david.calavera@gmail.com>

Add NewCredSshKeyFromMemory to the credentials helpers.

---

commit.go

The existing `Commit.Message()` returns the trimmed commit message. In some cases
it is important to retrieve the exact commit message, even if it contains surrounding
newlines.
This adds a new `Commit.RawMessage()` to be able to do that.

Add method to fetch raw commit message

---

odb.go
refdb.go

Offers a solution to #314 
The change is simple and allows usage of NewOdbBackendFromC and NewRefdbBackendFromC.

Make New*BackendFromC take unsafe.Pointer as argument

---

features.go
git.go

We ask libgit2 whether it's thread-safe and we panic if it's not. Go's runtime's interaction with C code is inherently multi-threaded so we're bound to crash anyway. Do it at the start with a message that describes the issue.
I'm not sure how to do automated testing for this without incurring twice the cost of building libgit2, but It Works On My Machine.
This fixes #329

Add Feature query support & panic if libgit2 is not thread-aware

---

.gitmodules
Makefile
git.go
git_dynamic.go
git_static.go

This lets us specify which set of rules to link to libgit2 we'll use during
build. Together with the changes to the Makefile, this lets you specify
make install
or
make install-static
to build either dynamically against the system-provided library or against the
version specified in the submodule.
The dynamic linking against the system library is still the default in order to
allow for the Go toolchain to build it when it's used as a dependency.

Link dynamically or statically depending on build flags

---

git.go
rebase.go
rebase_test.go

Hello,
I needed `rebase` services to be wrapped in `git2go` so I propose this PR.
Should I propose it on `next` branch instead of `master` ?
There's still some work though : 
- test what happens when a conflict arise during the rebase chain
- manage `git_rebase_options` and wrap `git_rebase_init_options(...)`
- wrap `git_rebase_open(...)`
I'll probably do the test for merge conflicts as I will need it quite soon.
Other services are of no interest for me at the moment, let me know if you'd like them wrapped as I'm into the work. Shouldn't be too long.
Let me know what you think. Cheers.

Rebase wrapper

---

tree.go

This fixes a memory leak in the following methods:
* `Tree.EntryByName()`
* `Tree.EntryByPath()`
* `Tree.EntryById()`
This issue was previously reported in https://github.com/libgit2/git2go/issues/313
I decided to use `defer` calls because it's cleaner and more consistent with the conventions used inside the codebase (@carlosmn, you mentioned using a local var in #313).
In addition `go1.8` has [halved the costs of defer calls](https://golang.org/doc/go1.8#defer), I think correctness comes before speed (premature optimization).

Fix memleaks in Tree.EntryBy(Name/Path/Index), fixes #313

---

patch.go

Buffer allocated in Patch.String() was never freed

Fix memory leak in Patch.String()

---

repository.go

This adds the new flags for repository open that were introduced in 0.25 of libgit2.
REF: https://github.com/libgit2/libgit2/blob/3b4eb107c21eb855dd651bc2e5904c0b29ece9b7/CHANGELOG.md#api-additions-1

Add new repository open flags

---

.travis.yml
Makefile
git.go
git_dynamic.go
git_static.go

This hopes to aid in the tension between providing the latest but also being able to provide something that is installable without compilation of libgit2.
In order to keep up with the latest you need to compile, which means going outside of the Go tools. It is then not much of an extra step to run `make` or perform these steps yourself. If you have a different kind of building, you can also pass in the flag yourself.
If you're not interested in that but want to use a released version installed on the system, you already had to use the versioned branches, as even `master` before would just update from one to the other, requiring extra steps to handle that.
New versioned branches that come out of this will also have this capability which should make it easier to use a released version but …

Allow building statically via the "static" build tag

---

.travis.yml
remote.go

Especially in 1.8, the garbage collector can decide to finalize an object even
as we are in one of its methods. This means it can free a remote while we're in
one of its calls, as we're referencing the pointer inside the object, rather
than the `Remote` itself.

remote: add keep-alive and references to the repository

---

commit.go

As in the subject. The method ExtractSignature wraps git_commit_extract_signature. This is useful in gpg-signed commits, to retrieve the stuff which has been signed and the corresponding signature. This fixes #388

Added Commit.ExtractSignature to wrap git_commit_extract_signature

---

blame.go
blob.go
branch.go
checkout.go
cherrypick.go
commit.go
config.go
describe.go
diff.go
git.go
graph.go
ignore.go
index.go
merge.go
note.go
object.go
odb.go
packbuilder.go
patch.go
rebase.go
refdb.go
reference.go
repository.go
signature.go
stash.go
status.go
submodule.go
tag.go
tree.go
walk.go

Newer Go runtimes' GC is particularly eager and doesn't even consider the receiver as a reference. Thus in order for structs wrapping the pointers not to be freed while in the middle of us using them in a function call, we must make sure that the wrapping struct is kept alive until after we return from.
This seems to be the cause of #352, #334 and #356 and this should fix the other places where this might happen.

KeepAlive all the things

---

blame.go
blob.go
branch.go
checkout.go
cherrypick.go
commit.go
config.go
describe.go
diff.go
git.go
graph.go
ignore.go
index.go
merge.go
note.go
object.go
odb.go
packbuilder.go
patch.go
rebase.go
refdb.go
reference.go
repository.go
signature.go
stash.go
status.go
submodule.go
tag.go
tree.go
walk.go

These are the same changes as #393 but for v26. There are some keep-alives missing for `Commit` which would require a conversion to pointer receivers, which IIUC would be a breaking change.

KeepAlive all the things for v26

---

Makefile

It turns out we had been running CI without performing the thread locking check.

Deduplicate Makefile static target and add thread locking check

---

rebase.go
rebase_test.go

We were incorectly reporting `C.GIT_REBASE_NO_OPERATION` as an error code when
it is none. We should instead return it as the value. The compiler doesn't seem
to actually look at the sizes so instead we must recreate the value ourselves
with `^uint(0)`.
The error return is kept for API compatibility but should go away eventually.
This supersedes #385

rebase: correct the return values for CurrentOperationIndex

---

submodule.go

There is a breaking API change in [libgit2 0.26](https://github.com/libgit2/libgit2/releases/tag/v0.26.0).
I guess `CloneCheckoutStrategy` also can be removed.

clone_checkout_strategy removed

---

tree.go

I think `KeepAlive()` must be moved a bit down to protect `entry`.

tree: keep tree receiver alive as long as dependent entry is used

---

.travis.yml

This covers CVE-2018-11235 and forbids .gitmodules as symlinks.

vendor: update libgit2 to v0.27.1

---

reference.go

This fixes a leak that was apparently introduced in commit 55a109614151.

git2go: fix reference iterator leak

---

checkout.go

"use ours" instead of "user ours" to match upstream.

Fix typo in constant name

---

config.go
config_test.go

This is to fix issue #256. Removing parent from OpenOndisk from method signature which is not used.
**Risk:** Change in method signature will impact dependent programs so, there is need to plan how to incorporate this change.

Remove unused parameter in OpenOndisk #256

---

odb.go
odb_test.go

This change makes OdbReadStream.Read() comply with the usual io.Reader
semantics.

Return io.EOF on OdbReadStream.Read()

---

merge.go

While we're here, pull in comments as well.
While one can pop back and forth between godoc and libgit2 refs,
it's much nicer to have it in one place.
Note that MergeFileStyleSimplifyAlnum probably should have been called
merely MergeFileSimplifyAlnum (no "Style"). It's probably not worth
breaking backwards compatibility to fix it, but we avoid the mistake
going forwards.

merge: add missing MergeFileFlag constants

---

odb.go
odb_test.go

- Fix couple cgo issues in odb.Write() and odb.Hash(). This is the
same issue - and same solution - as repo.CreateBlobFromBuffer()
used to have.
- Add test for odb.Read()

git2go: small fixes to odb module

---

index.go

Simple PR that adds `index.Clear()`, which does nothing more than calling [`git_index_clear`](https://github.com/libgit2/libgit2/blob/bea65980c7a42e34edfafbdc40b199ba7b2a564e/include/git2/index.h#L404).

Add index.Clear() to clear the index object

---

packbuilder.go

This change adds support for Packbuilder.InsertFromWalk() from libgit2.

Add support for Packbuilder.InsertWalk()

---

git_static.go
script/build-libgit2-static.sh

When using the static linking option on platforms that use pkg-config,
use ONLY pkg-config to get the CFLAGS and LDFLAGS. This prevents pulling
in dependencies and flags for any non-vendored version that may be
present on the host.
The main practical effect of this is that if someone doesn't need/want
any sort of remote access support at all they can completely disable
libcurl, libssh2, libssl, etc and produce a smaller/simpler binary and
greatly simplify their build-time dependencies. When done properly, the
generated pkg-config file will tell cgo everything it needs to know.
This also prevents confusion if there is a system copy of libgit2 that
is being given priority over the vendored build.

static: use pkg-config exclusively when using it

---

index_test.go

This includes updating the `Index.WriteTreeTo` test as it was abusing an
oversight of the object creation safety checks and creating a tree referencing
a non-existent blob. Instead we update it to the primary purpose of this method
which is to write into a repository from an unattached index.

Bump vendored libgit2 to fba70a9d5f

---

reset_test.go

A `defer cleanupTestRepo()` was missing.

Clean up one leaked temporary directory

---

.gitignore
git_static.go
script/build-libgit2-static.sh

This change:
* Uses the installed version of both the library and the pkgconfig file,
which fixes path resolution on Ubuntu Xenial.
* Uses quoting liberally so that paths with spaces in them are correctly
handled.
* Moves the build+install directories to static-build/ in the git2go
repository to avoid having a dirty vendor/libgit2 checkout.

Improve the static build script

---

go.mod

This change adds a `go.mod` file. An empty file is sufficient since this
project has no external dependencies. For people that want to use the static
version of libgit2, this module can be vendored and the following can be added
to their `go.mod` file:
replace github.com/libgit2/git2go => ./vendor/github.com/libgit2/git2go

Add support for Go 1.11 modules

---

commit.go

This adds MessageEncoding() method to Commit struct, which simply returns the result of git_commit_message_encoding function.
I want to add git_commit_message_encoding function support because I encountered a problem where commit messages must be assured of being UTF-8 to pass them through gRPC.
For the purpose, I need to know the encoding of commit messages.
Thanks.

Add git_commit_message_encoding support

---

git_dynamic.go

A few months ago a PR has been made to [support v28](https://github.com/libgit2/git2go/commit/5fda6dd90191b1c51a1785ad7cabd2fd5b05e802), but the guard around the dynamic lib hasn't been updated. This PR fixes that.

fix invalid guard forcing v27 instead of v28

---

script/build-libgit2-static.sh

The ROOT variable is not being set correctly. Need to use dirname against
$0 as well as only go up one directory instead of two.

script/build-libgit2-static.sh: correctly set ROOT

---

diff.go

Without a parameter name, the float64 param is pretty inscrutable.

provide param names in DiffForEachFileCallback

---

tag.go
tree.go

Fixes #513 - Segfault during tree walk

---

go.mod

This is compliant with
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher,
which says
```
Major branch: Update the go.mod file to include a /v3 at the end of the
module path in the module directive (e.g., module
github.com/my/module/v3). Update import statements within the module to
also use /v3 (e.g., import "github.com/my/module/v3/mypkg"). Tag the
release with v3.0.0.
```
This also means that unfortunately we cannot keep using libgit2's exact
version number (plus a build number for git2go purposes, since go only
recognizes vMAJOR.MINOR.PATCH format).
(Tentatively) fixes: #536

Add the /v28 suffix to go.mod

---

mempack.go

This uprevs libgit2 to the latest and greatest. Notably,
* Fixes the interface of `git_mempack_reset`, since it now returns an
`int` instead of being `void`.
Fixes: #533

Uprev libgit2

---

.github/workflows/ci.yml
.gitignore
.travis.yml
Makefile
script/build-libgit2-dynamic.sh
script/build-libgit2-static.sh
script/build-libgit2.sh

This change:
* Updates the GitHub actions so that they run different commands for the
dynamic and static flavors of libgit2.
* Updates the .travis.yml file so that it does roughly the same as the
GitHub actions.
* Adds the release-* branches to the CI configurations.

Update CI configuration

---

repository.go

`repository.LookupXxx()` allocate new go `Object`s that have a reference
to a `C.git_object`. Those are then duplicated with `git_object_dup()`,
so the original `Object`s linger unnecessarily until the Go GC kicks in.
This change explicitly calls `Free()` on the originals to avoid
unnecessary accumulation of garbage.

Free() the copies of repository.LookupXxx()

---

credentials.go
remote.go

This change adds Cred.Free() and finalizers to prevent memory leaks. It
also makes the interface for Cred more idiomatic and return actual
errors intead of ints.

Fix the Cred interface

---

odb.go
odb_test.go

This change adds support for odb.NewOdbBackendLoose(). This, together
with the git.Packbuilder, can do what Mempack does with a lot less
memory.

Add odb.NewOdbBackendLoose()

---

diff.go

This change makes the underlying type of DiffFlag be uint32 instead of
int. That makes it possible to build on 32-bit systems.
Fixes: #487

Fix the DiffFlag type

---

git.go

I've added an additional constant with the correct spelling. I did this
rather than removing the existing constant to avoid breaking existing
code with the misspelled name.

Resolves issue #541 - typo in error code 'ErrAmbigious'

---

.travis.yml

This change:
* Stops running tests under Go 1.1 and Go 1.2, since Travis no longer
supports them.
* Stops running tests under Go tip, since Go 1.6 changed the rules for
pointers changed and the code no longer works for that version (or
beyond).
* Uprevs libgit (test) to v0.22.3.

Update the Travis setup for release-0.22

---

.travis.yml
config_test.go
script/install-libgit2.sh

This change:
* Stops running tests under Go 1.1 and Go 1.2, since Travis no longer
supports them.
* Uprevs libgit (test) to v0.23.4.

Update the Travis setup for release-0.23

---

.travis.yml
config_test.go
script/install-libgit2.sh

This change:
* Stops running tests under Go 1.1 and Go 1.2, since Travis no longer
supports them.
* Stops running tests under Go tip. Go 1.8+ requires runtime.KeepAlive()
to keep some of the references alive across CGo invocations, but that
was introduced in Go 1.7, and that would break older Go versions.
* Fixes a formatting bug that was breaking under newer Go releases.
* Uprevs libgit (test) to v0.24.6.

Update the Travis setup for release-0.24

---

go.mod

This is the second take on trying to tag the current release with a Go
version.

Add the version number to go.mod

---

diff.go
index.go
merge_test.go
settings.go
settings_test.go

It is not Go idiomatic to put Get into the getter's name ([see here](https://golang.org/doc/effective_go.html#Getters)).
Based on the discussion with @lhchavez on Slack. He suggested the renaming and adding backward compatibility.

Rename methods with Get prefix

---

message.go
message_test.go

Adds a wrapper for git_message_trailers which returns a slice of trailer
structs.
First pull request for git2go & first use of cgo, criticism welcomed, thanks!

Add support for parsing git trailers

---

merge.go

This change adds two missing merge flags MergeTreeSkipREUC and MergeTreeNoRecursive.
Thanks.

Provide missing merge flags

---

script/build-libgit2.sh

This change removes the `LIB_INSTALL_DIR` and `INCLUDE_INSTALL_DIR` from
the `script/build-libgit2.sh` script, since they are now unneeded and
just print a warning if they are used.

Remove a couple of now-unnecessary CMake defines

---

git.go
handles.go

This change adds the Shutdown() method, so that the library can be
cleanly shut down. This helps significanly reduce the amount of noise in
the leak detector.

Add a way to cleanly shut down the library

---

diff.go
patch.go

This change makes the DiffNotifyCallback always use an "unowned"
*git.Diff that does _not_ run the finalizer. Since the underlying
git_diff object is still owned by libgit2, we shouldn't be calling
Diff.Free() on it, even by accident, since that would cause a whole lot
of undefined behavior.
Now instead of storing a reference to a *git.Diff in the intermediate
state while the diff operation is being done, create a brand new
*git.Diff for every callback invocation, and only create a fully-owned
*git.Diff when the diff operation is done and the ownership is
transfered to Go.

Fix a potential use-after-free in DiffNotifyCallback

---

README.md
git_bundled_static.go
git_system_dynamic.go
git_system_static.go

This change allows to link the system version of libgit2 statically.
Since `-tags static` is already used for the bundled version of the
library and to avoid breaking old workflows, `-tags
static,system_libgit2` is now used to select that.
This means that the valid combinations are:
| Flag                          | Effect                                        |
|-------------------------------|-----------------------------------------------|
| _No flags_                    | Dynamically-linked against the system libgit2 |
| `-tags static,system_libgit2` | Statically-linked against the system libgit2  |
| `-tags static`                | Statically-linked against the bundled libgit2 |
Note that there is no way to express dynamically linking against the
bundled libgit2 because that makes …

Revamp the ways in which the library can be built

---

remote.go

Prior to this change you could not specifiy proxy options on the
FetchOptions struct, which made it impossible to specify a proxy for an
initial clone. This change adds the ProxyOptions to the FetchOptions
struct so you can go through a proxy when cloning.

FetchOptions: add ability to specify ProxyOptions

---

script/build-libgit2.sh

Upstream libgit2 has migrated to use the GNUInstallDirs module to decide
where things will be installed to by default. While it improves
consistency with the host system, we're not really after that when
building the vendored libgit2 library, and in fact libgit2.{a,pc} may
now be installed into a different directory than before as it started to
depend on the host platform.
Fix this by explicitly specifying that we want the library and pkgconfig
file to be installed into a plain "lib/" directory.

Fix installation of libgit2 into wrong libdir

---

blob.go
blob_test.go

This adds IsBinary() func to Blob struct, which simply returns the result of git_blob_is_binary function.
Refs: https://libgit2.org/libgit2/#HEAD/group/blob/git_blob_is_binary
Issue: Add support for git_blob_is_binary #426
Fixes: #426

Add support for git_blob_is_binary

---

status.go
status_test.go

`git_status_byindex` can return a null pointer if there is no statuses.

Fix null pointer dereference in status.ByIndex

---

.github/workflows/ci.yml
README.md
script/build-libgit2.sh

This change:
* Builds the library with Go 1.14, too.
* Builds the non-legacy tests with Ubuntu Focal (20.04).
* Adds testing for system-wide libraries, both static and dynamic
versions.
* Fixes a typo in the README.

Refresh the GitHub Actions CI

---

.github/workflows/backport.yml
.github/workflows/tag.yml

This change adds:
* `tag.yml`: Creates a new tag every time the master or a release branch
is pushed.
* `backport.yml`: Creates a cherry-pick in older release branches to
keep them up to date with little cost.

Add two more GitHub Actions workflows

---

diff.go

As it turns out, the CI was not enabled for the release-0.28 branch.

Fix the build

---

merge.go

The `recursion_limit` merge option provided by libgit2 is currently not
exposed and thus inaccessible to Git2Go users. Let's expose it to let
users control creation of recursive merge bases.

merge: Expose recursion limit merge option

---

git.go

libgit2 stores the lookup paths for gitconfig files in its global state.
This means that after a program changes its effective uid libgit2 will
still look for gitconfig files in the home directory of the original
uid. Expose a way to call C.git_libgit2_init so a user can reinitialize
the libgit2 global state.

Add a ReInit function

---

script/build-libgit2.sh

This change aims to enable us to set the `VENDORED_PATH` as an environment variable and failback to the default value if the environment variable is not set. Thus, this change should not break current behavior.
This will enable using the script to build libgit2 form source code downloaded manually.
Example:
```sh
LIBGIT2_VER="1.0.1"
DOWNLOAD_URL="https://codeload.github.com/libgit2/libgit2/tar.gz/v${LIBGIT2_VER}""
LIBGIT2_PATH="${HOME}/libgit2-${LIBGIT2_VER}"
wget -O "${LIBGIT2_PATH}.tar.gz" "$DOWNLOAD_URL"
tar -xzvf "${LIBGIT2_PATH}.tar.gz"
VENDORED_PATH=$LIBGIT2_PATH sh ./script/build-libgit2.sh --static
```

Enable set the VENDORED_PATH for libgit2

---

script/build-libgit2.sh

The current `CMAKE_INSTALL_PREFIX` value for the `system` build mode is `/usr`. However, in`macOS` as an example, you cannot write to `/usr` without `sudo` permission.
Enable changing the value to `/usr/local` (or any other path). This change makes the script use the value of the environment variable `SYSTEM_INSTALL_PREFIX` to select the installation path.  If the variable is not set, it fallback to the path `/usr`.

Enable change the system install path

---

repository.go

While we already have wrappers for `git_object_lookup`, there are none
yet for the prefixed variant where only the first n bytes of the OID are
used for the lookup. This commit adds them.

repository: Implement wrappers for `git_object_lookup_prefix`

---

blame.go
checkout.go
cherrypick.go
clone.go
describe.go
diff.go
merge.go
rebase.go
remote.go
revert.go
stash.go
status.go
submodule.go

This PR move form linking against the deprecated `init_options` functions to the renamed `options_init` functions.
For more context see libgit2/libgit2@0b5ba0d744e69da5dc8c08d167c83dd87ed83af2 and libgit2/libgit2@c6184f0c4b209e462bf3f42ab20df2d13d8ee918.

Use un-deprecated options init functions from libgit2

---

diff_test.go

This change adds explicit `.Free()` calls in `TestApplyDiffAddFile()`.
It was discovered in #657 that some objects were not explicitly being
freed, so this fixes that!

Make `TestApplyDiffAddFile()` explicitly `.Free()` stuff

---

diff.go
diff_test.go
git.go

Adds bindings to the git_apply_to_tree function that allows applying
a diff directly to a tree.
Should this get merged, when do you anticipate a new release that includes these changes?

apply: Add bindings for git_apply_to_tree

---

.github/workflows/ci.yml
.travis.yml

This change:
* Makes the Travis tests only run tip, since the rest of the Go versions are better served by GitHub Actions.
* Use Go 1.15 in the CI. This has been released for a while.

CI refresh

---

.github/workflows/ci.yml
.travis.yml

This change:
* Makes the Travis tests only run tip, since the rest of the Go versions are better served by GitHub Actions.
* Use Go 1.15 in the CI. This has been released for a while.
(cherry picked from commit f83530b18dc46867ed06fc261b309b8b545a3b6f)

CI refresh (#666)

---

.github/workflows/backport.yml
README.md
git_bundled_static.go
git_system_dynamic.go
git_system_static.go
go.mod

The libgit2 `v1.1.0` is released two weeks ago. This PR allows `git2go` to link against the new version.

Create v31 to support libgit2 v1.1.x

---

settings.go
settings_test.go

Add a binding to enable/disable hash verification using the `GIT_OPT_ENABLE_STRICT_HASH_VERIFICATION` option.
Change type: #minor

Implement an option to control hash verification

---

settings.go
settings_test.go

Add a binding to enable/disable hash verification using the `GIT_OPT_ENABLE_STRICT_HASH_VERIFICATION` option.
Change type: #minor
(cherry picked from commit c3664193f3c05bd6ae48f153c6c41cd7d7a3d98b)

feat: Implement an option to control hash verification (#671)

---

.github/workflows/backport.yml

This change uses the correct branch name (`release-1.0`) to backport
changes into the v1.0 branch.

Use the correct branch name for backporting into v1.0

---

blame.go

The `GIT_BLAME_USE_MAILMAP` blame option flag was introduced in libgit2 v0.28.
Change type: #minor

Add GIT_BLAME_USE_MAILMAP flag

---

blame.go

The `GIT_BLAME_IGNORE_WHITESPACE` blame option flag was introduced in libgit2 v1.1.0.
Change type: #minor

Add GIT_BLAME_IGNORE_WHITESPACE flag

---

reference.go
reference_test.go

Not sure about the buffer allocation for passing to `git_reference_normalize_name`: Is using `malloc` correct? Is the size correct, or should it be a loop with retries with some increasing buffer size (But the function doesn't seem to tell you how big it should be...)?

Add ReferenceNormalizeName

---

remote.go

Seems libgit2 had SHA256 fingerprint support since libgit2 v0.99.0; https://github.com/libgit2/libgit2/pull/5307
This means that if you run libssh2 1.9.0 or newer, most likely the CertificateCheckCallback doesn't actually work for ssh/hostkey based remotes, because the fingerprint is not available.
~In addition I don't think we should be doing memcpy of the structures not set by libgit2.~
I have a test for it as well, but you can't anonymously connect over ssh, so I need a deploy key (which is read only) from https://github.com/libgit2/TestGitRepository. I had intended for the test to be automatically skipped if the ssh feature was not available, and check the hostkey's against the fingerprints from https://api.github.com/meta
If you could provide said deploy key, I'd be happy to add the …

Expose GIT_CERT_SSH_SHA256

---

.github/workflows/ci.yml
git_bundled_static.go
git_system_dynamic.go
git_system_static.go
script/build-libgit2.sh

relax version check

---

.github/workflows/ci.yml
git_bundled_static.go
git_system_dynamic.go
git_system_static.go
script/build-libgit2.sh

Backport of #696.
----
The major version must still be an exact match since libgit2 uses
semantic versioning and changes to the major number indicate backwards
incompatible changes to the API.
Fixes: #695
(cherry picked from commit 1fabe95fb7275df980ff6ab03fb85eac91c5849d)

[release-1.0] Relax libgit2 minor version check (#696)

---

checkout.go
cherrypick.go
clone.go
diff.go
diff_test.go
git.go
index.go
merge.go
odb.go
packbuilder.go
patch.go
rebase.go
remote.go
remote_test.go
reset.go
revert.go
stash.go
submodule.go
tag.go
tree.go
wrapper.c

This change is a preparation for another change that makes all callback
types return a Go error instead of an error code / an integer. That is
going to make make things a lot more idiomatic.
The reason this change is split is threefold:
a) This change is mostly mechanical and should contain no semantic
changes.
b) This change is backwards-compatible (in the Go API compatibility
sense of the word), and thus can be backported to all other releases.
c) It makes the other change a bit smaller and more focused on just one
thing.
Concretely, this change makes all callbacks populate a Go error when
they fail. If the callback is invoked from the same stack as the
function to which it was passed (e.g. for `Tree.Walk`), it will preserve
the error object directly into a struct that also holds the …

Refactor all callbacks

---

checkout.go
cherrypick.go
clone.go
diff.go
diff_test.go
git.go
index.go
merge.go
odb.go
packbuilder.go
patch.go
rebase.go
remote.go
remote_test.go
reset.go
revert.go
stash.go
submodule.go
tag.go
tree.go
wrapper.c

This change is a preparation for another change that makes all callback
types return a Go error instead of an error code / an integer. That is
going to make make things a lot more idiomatic.
The reason this change is split is threefold:
a) This change is mostly mechanical and should contain no semantic
changes.
b) This change is backwards-compatible (in the Go API compatibility
sense of the word), and thus can be backported to all other releases.
c) It makes the other change a bit smaller and more focused on just one
thing.
Concretely, this change makes all callbacks populate a Go error when
they fail. If the callback is invoked from the same stack as the
function to which it was passed (e.g. for `Tree.Walk`), it will preserve
the error object directly into a struct that also holds the …

Refactor all callbacks (#700)

---

.github/workflows/ci.yml
Makefile
script/build-libgit2.sh

This change makes the test be verbose and the test use parallelization
if possible (when using gmake to build).

Build improvements

---

clone.go
clone_test.go
git_test.go
object.go
push_test.go
reference.go
remote.go
remote_test.go
repository.go

This change makes sure that pointer handles are correctly cleaned up
during tests.

Ensure that no pointer handles leak during the test

---

checkout.go
cherrypick.go
clone.go
clone_test.go
diff.go
git_test.go
indexer.go
merge.go
object.go
odb.go
patch.go
push_test.go
rebase.go
reference.go
remote.go
remote_test.go
repository.go
reset.go
revert.go
stash.go
submodule.go
wrapper.c

This change:
* Gets rid of the `.toC()` functions for Options objects, since they
were redundant with the `populateXxxOptions()`.
* Adds support for `errorTarget` to the `RemoteOptions`, since they are
used in the same stack for some functions (like `Fetch()`). Now for
those cases, the error returned by the callback will be preserved
as-is.

More callback refactoring

---

checkout.go
cherrypick.go
clone.go
diff.go
indexer.go
merge.go
odb.go
patch.go
rebase.go
remote.go
reset.go
revert.go
stash.go
submodule.go
wrapper.c

This change:
* Gets rid of the `.toC()` functions for Options objects, since they
were redundant with the `populateXxxOptions()`.
* Adds support for `errorTarget` to the `RemoteOptions`, since they are
used in the same stack for some functions (like `Fetch()`). Now for
those cases, the error returned by the callback will be preserved
as-is.
(cherry picked from commit 10c67474a89c298172a6703b91980ea37c60d5e5)

More callback refactoring (#713)

---

remote.go
remote_test.go

Support git_remote_create_with_opts

---

git.go
odb_test.go

Use `err` instead of `error` as a variable name for errors

---

index.go

From gorelease:
```
Compatible changes:
- IndexTime.Nanoseconds: added
- IndexTime.Seconds: added
```
There are no extra tests because there isn't really anything to test
closes #304

Make index time fields public

---

Build_bundled_static.go

When building on Windows with MinGW using "bundled static" config, I am getting following errors
```
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\vbuzu\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -tags static -o C:\Users\vbuzu\AppData\Local\Temp\___1TestConfigLookups_in_github_com_libgit2_git2go_v31.exe github.com/libgit2/git2go/v31 #gosetup
C:/Users/vbuzu/projects/vladimir-buzuev/git2go/static-build/install/lib//libgit2.a(index.c.obj): In function `write_extension':
C:/Users/vbuzu/projects/vladimir-buzuev/git2go/vendor/libgit2/src/index.c:2865: undefined reference to `__imp_htonl'
C:/Users/vbuzu/projects/vladimir-buzuev/git2go/static-build/install/lib//libgit2.a(index.c.obj): In function `read_header':
C:/Users/vbuzu/projects/vladimir-buzuev/git2go/vendor/libgit2/src/index …
```

fix bundled static build on Windows/MinGW

---

.github/workflows/ci.yml

These builds are no longer working because some of the dependencies now
require newer versions of Go. Seems like the ecosystem has moved to Go
1.11+, so we are now forced to follow suit.

Remove the legacy builders

---

.github/workflows/backport.yml
.github/workflows/ci.yml

These builds are no longer working because some of the dependencies now
require newer versions of Go. Seems like the ecosystem has moved to Go
1.11+, so we are now forced to follow suit.
(cherry picked from commit df7084d36a771e4ef2a418c7d3c4367d920e4cf3)

Remove the legacy builders (#776)

---

commit.go
repository.go
repository_test.go

This commit adds the Go binding for `git_commit_create_buffer`. This
will be used to support the 1.2.0 commit create callback.

Add `Repository.CreateCommitBuffer`

---

commit.go
repository.go
repository_test.go

This commit adds the Go binding for `git_commit_create_buffer`. This
will be used to support the 1.2.0 commit create callback.
(cherry picked from commit fbaf9d1d1ae0bb7b6e7ed9044945d4c9322d4c76)

Add `Repository.CreateCommitBuffer` (#781)

---

.github/workflows/ci.yml
Build_bundled_static.go
Build_system_dynamic.go
Build_system_static.go
script/build-libgit2.sh

We can't yet ship a fully libgit2 v1.2.0-compatible library due to a
missing public symbol, but we can allow the v1.1.0-era codebase to link
against libgit2 v1.2.0 in the meantime.

Declare forward-compatibility with libgit2 v1.2.0  #minor

---

clone.go
git.go
git_test.go
remote.go
remote_test.go
repository.go
transport.go
transport_test.go
wrapper.c

This change adds support for git smart transports. This will be then
used to implement http, https, and ssh transports that don't rely on the
libgit2 library.

Add support for custom smart transports

---

clone.go
git.go
git_test.go
remote.go
repository.go
transport.go
transport_test.go
wrapper.c

This change adds support for git smart transports. This will be then
used to implement http, https, and ssh transports that don't rely on the
libgit2 library.
(cherry picked from commit f1fa96c7b7f548389c7560d3a1a0bce83be56c9f)

Add support for custom smart transports (#806)

---

.github/workflows/backport.yml
.github/workflows/ci.yml
Build_bundled_static.go
Build_system_dynamic.go
Build_system_static.go
README.md
checkout.go
cherrypick.go
clone.go
clone_test.go
commit.go
deprecated.go
git.go
go.mod
index.go
index_test.go
indexer_test.go
merge.go
odb_test.go
rebase.go
reference.go
reference_test.go
remote.go
remote_test.go
revert.go
revert_test.go
submodule.go
submodule_test.go
tree.go
wrapper.c

This commit introduces libgit2 v1.2.0 to git2go, which brings a large
number of [bugfixes and
features](https://github.com/libgit2/libgit2/releases/tag/v1.2.0).
This also marks the start of the v32 release.
Fixes: #775

libgit2 v1.2.0 #major

---

remote.go
transport.go

This change exposes the raw SSH hostkey and the ssh.PublicKey into the
CertificateCheckCallback, so that callers can do better validations.

Expose the ssh.PublicKey into the CertificateCheckCallback

---

odb.go

This change exposes the binding for `git_odb_write_multi_pack_index()`.

Add support for Odb.MultiPackIndex()

---

graph.go
graph_test.go

This change exposes the binding for `git_graph_reachable_from_any()`.

Add support for Repository.ReachableFromAny()

---

script/build-libgit2.sh

This change allows the caller to set the `USE_CHROMIUM_ZLIB=ON`
environment variable to use the Chromium implementation of zlib when
building libgit2.

Allow building libgit2 with Chromium zlib

---

tree.go
tree_test.go

It is now possible to skip expanding an entry in `tree.Walk()` by
returning `TreeWalkSkip`, in addition to stopping altogether by
returning a non-nil error.
Fixes: #837

Allow skipping an entry expansion in `tree.Walk()`

---

ssh.go

Before this change, the commands sent to the git server were of the form:
```
git-upload-pack "/bar/test-reponame"
```
This resulted in the git server ([gitkit](https://github.com/sosedoff/gitkit)) returning error:
`error parsing command: invalid git command`
This change replaces the double quotes with single quotes:
```
git-upload-pack '/bar/test-reponame'
```
Using git smart transport via managed ssh transport against gitkit, fails with the following errors:
```console
2021/11/07 21:57:24 ssh: incoming exec request: git-upload-pack "/bar/test-reponame"
2021/11/07 21:57:24 ssh: payload 'git-upload-pack "/bar/test-reponame"'
2021/11/07 21:57:24 ssh: error parsing command: invalid git command
```
Resulting in a clone failure: `unable to clone: EOF`.
Using ssh transport based on the libgit2 …

Make ssh commands used in the git smart transport compatible with libgit2

---

.github/workflows/ci.yml
Makefile
git.go

Added `stringer` annotations to `git.go` for `ErrorClass` and
`ErrorCode`. Added `generate` rule for `Makefile` to generate
string representations for these types (first building cgo files
in `_obj` dir to get C constants). Finally, updated `ci` actions
workflow to check that generated files are up to date.
Fixes: #543

Generate stringer files automatically

---

.github/workflows/ci.yml
Makefile
git.go

Added `stringer` annotations to `git.go` for `ErrorClass` and
`ErrorCode`. Added `generate` rule for `Makefile` to generate
string representations for these types (first building cgo files
in `_obj` dir to get C constants). Finally, updated `ci` actions
workflow to check that generated files are up to date.
Fixes: #543
(cherry picked from commit 5e35338d58b589939b599c98ec9e6b44f94de20a)

Generate stringer files automatically (#841)

---

settings.go
settings_test.go

This adds support for the GIT_OPT_ENABLE_FSYNC_GITDIR option in libgit2.
https://github.com/libgit2/libgit2/blob/v0.28.1/include/git2/common.h#L357

Add EnableFsyncGitDir to enable synchronized writes to the gitdir

---

remote.go

Analog to https://github.com/libgit2/git2go/pull/623 but for push operations rather than fetch.

Add ability to specify ProxyOptions for push operations

---

README.md

The GoDoc link currently refers to the initial version of this package, but usually folks are looking
for whatever matches the current main branch. This should be updated whenever the package
version changes.

readme: link to godoc for current main branch

---

rebase.go
rebase_test.go

Add a new wrapper for `git_rebase_inmemory_index()`, which can be used
to retrieve the index for an in-memory rebase.

rebase: Add wrapper for `git_rebase_inmemory_index()`

---

refspec.go
refspec_test.go

This adds support for the parse, accessor, and transform functions for [refspec](https://libgit2.org/libgit2/#v1.3.0/group/refspec) objects. It's a direct port of the C API.

Add refspec bindings

---

http.go

This prevents error "read/write on closed pipe".
Go's http.client::send() always closes req.Body, so if the first request attempt
is unsuccessful, any subsequent requests after calling the `CredentialsCallback`
will attempt to read/write on a closed pipe.

Set BasicAuth in http.go only if username and password are not empty

---

.github/workflows/backport.yml
.github/workflows/ci.yml
Build_bundled_static.go
Build_system_dynamic.go
Build_system_static.go
README.md
go.mod
http.go
remote.go
transport.go

Update libgit2 to v1.5.0. Replace `SmartProxyOptions()` with `SmartRemoteConnectOptions()`.
Fixes: https://github.com/libgit2/git2go/issues/899
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>

libgit2 v1.5.0 #major

---

.github/workflows/tag.yml

This has been failing for a while because of some changes in `git`.

Fix the `github-tag-action` workflow
